name: Build QModem Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出仓库代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 2. 初始化 OpenWrt 构建环境
      - name: 初始化 OpenWrt 构建环境
        run: |
          sudo apt update && sudo apt install -y build-essential libncurses-dev flex bison libssl-dev
          git clone https://github.com/openwrt/openwrt.git -b v22.03.5 ./openwrt
          cp feeds.conf.default openwrt/feeds.conf.default
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p qmodem

      # 3. 配置编译目标（MT7621）
      - name: 配置编译目标（MT7621）
        run: |
          cd openwrt
          make menuconfig
        # 注意：`make menuconfig` 是交互式命令，GitHub Actions 中无法直接运行！
        # 需要手动配置或通过脚本预设配置文件（见下方说明）

      # 4. 开始编译 QModem 插件
      - name: 开始编译 QModem 插件
        run: |
          cd openwrt
          make package/qmodem/compile V=s

      # 5. 打包并上传 IPK 文件
      - name: 打包并上传 IPK 文件
        uses: actions/upload-artifact@v3
        with:
          name: qmodem-ipk
          path: openwrt/bin/targets/mt7621/generic/packages/luci-app-qmodem_*.ipk
