name: Build QModem for MT7621

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout your OpenWrt fork
      uses: actions/checkout@v4
      with:
        repository: iRyanKC/openwrt
        path: openwrt

    - name: Checkout QModem feed
      uses: actions/checkout@v4
      with:
        repository: FUjr/QModem
        path: qmodem-feed

    - name: Prepare build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev git python3 python3-distutils
        cd openwrt
        cp -r ../qmodem-feed/* package/qmodem/  # 将QModem源码放入正确位置

    - name: Configure for Xiaomi Mi Router 3G
      run: |
        cd openwrt
        cat > .config <<EOF
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mir3g=y
CONFIG_PACKAGE_luci-app-qmodem=y
CONFIG_PACKAGE_luci-app-qmodem-sms=y
EOF
        make defconfig

    - name: Build packages
      run: |
        cd openwrt
        make -j$(nproc) package/qmodem/compile

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qmodem-packages
        path: openwrt/bin/packages/*/base/*qmodem*.ipk
