name: Build QModem Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: 检出仓库
        uses: actions/checkout@v4

      # 2. 初始化 OpenWrt 构建环境
      - name: 初始化 OpenWrt 构建环境
        run: |
          sudo apt update && sudo apt install -y build-essential libncurses-dev flex bison libssl-dev
          git clone https://github.com/openwrt/openwrt.git -b v22.03.5 ./openwrt
          cp feeds.conf.default openwrt/feeds.conf.default
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a -p qmodem

      # 3. 编译 QModem 插件
      - name: 编译 QModem 插件
        run: |
          cd openwrt
          make package/qmodem/compile V=s

      # 4. 上传 IPK 文件（关键修复点：升级到 v4）
      - name: 上传 IPK 文件
        uses: actions/upload-artifact@v4  # ← 此处从 v3 升级到 v4
        with:
          name: qmodem-ipk
          path: openwrt/bin/targets/mt7621/generic/packages/luci-app-qmodem_*.ipk
