name: Build QModem for MT7621

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openwrtorg/sdk:mt7621  # 指定你的路由器芯片 SDK

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare OpenWrt SDK
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add QModem feed
      run: |
        echo 'src-git qmodem https://github.com/FUjr/QModem.git;main' >> feeds.conf.default
        ./scripts/feeds update qmodem
        ./scripts/feeds install -a -p qmodem
        ./scripts/feeds install -a -f -p qmodem  # 强制覆盖

    - name: Configure packages
      run: |
        echo "CONFIG_TARGET_ramips=y" > .config
        echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
        echo "CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mir3g=y" >> .config
        
        # 选择 QModem 组件
        echo "CONFIG_PACKAGE_luci-app-qmodem=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-qmodem-sms=y" >> .config
        # 添加其他需要的组件（可选）
        # echo "CONFIG_PACKAGE_luci-app-qmodem-mwan=y" >> .config
        # echo "CONFIG_PACKAGE_luci-app-qmodem-ttl=y" >> .config
        
        make defconfig

    - name: Build packages
      run: make package/qmodem/compile -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qmodem-packages
        path: bin/packages/*/base/*qmodem*.ipk
